/**
 * Animal Crossing API
 * Swagger page for the Animal Crossing API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
export interface MonthsAvaliable {
    jan: boolean | undefined;
    feb: boolean | undefined;
    mar: boolean | undefined;
    apr: boolean | undefined;
    may: boolean | undefined;
    jun: boolean | undefined;
    jul: boolean | undefined;
    aug: boolean | undefined;
    sep: boolean | undefined;
    oct: boolean | undefined;
    nov: boolean | undefined;
    dec: boolean | undefined;
}

export interface CritterCollectionModel { 
    id: number;
    name: string;
    value: number;
    locationName: string;
    location: number;
    shadowSize: number;
    shadowSizeName: string;
    time: string;
    catchStartTime: Array<number>;
    catchEndTime: Array<number>;
    monthsAvailable: MonthsAvaliable;
    rarity: number;
    rarityName: string;
    weather: string;
}