/**
 * Animal Crossing API
 * Swagger page for the Animal Crossing API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type FishLocation = 1 | 2 | 3 | 4 | 5 | 6;

export const FishLocation = {
    NUMBER_1: 1 as FishLocation,
    NUMBER_2: 2 as FishLocation,
    NUMBER_3: 3 as FishLocation,
    NUMBER_4: 4 as FishLocation,
    NUMBER_5: 5 as FishLocation,
    NUMBER_6: 6 as FishLocation
};