/**
 * Animal Crossing API
 * Swagger page for the Animal Crossing API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type Weather = 1 | 2 | 3 | 4;

export const Weather = {
    NUMBER_1: 1 as Weather,
    NUMBER_2: 2 as Weather,
    NUMBER_3: 3 as Weather,
    NUMBER_4: 4 as Weather
};