import { ImageSourcePropType } from "react-native";

export interface IDictionary {
    [name: string]: ImageSourcePropType;
}

const ArtworkImages: IDictionary = {};
ArtworkImages["Fake Academic Painting"] = require('./Artwork/FakeAcademicPainting.png');
ArtworkImages["Academic Painting"] = require('./Artwork/RealAcademicPainting.png');
ArtworkImages["Fake Amazing Painting"] = require('./Artwork/FakeAmazingPainting.png');
ArtworkImages["Amazing Painting"] = require('./Artwork/RealAmazingPainting.png');
ArtworkImages["Fake Basic Painting"] = require('./Artwork/FakeBasicPainting.png');
ArtworkImages["Basic Painting"] = require('./Artwork/RealBasicPainting.png');
ArtworkImages["Calm Painting"] = require('./Artwork/RealCalmPainting.png');
ArtworkImages["Common Painting"] = require('./Artwork/RealCommonPainting.png');
ArtworkImages["Dynamic Painting"] = require('./Artwork/RealDynamicPainting.png');
ArtworkImages["Fake Detailed Painting"] = require('./Artwork/FakeDetailedPainting.png');
ArtworkImages["Detailed Painting"] = require('./Artwork/RealDetailedPainting.png');
ArtworkImages["Fake Famous Painting"] = require('./Artwork/FakeFamousPainting.png');
ArtworkImages["Famous Painting"] = require('./Artwork/RealFamousPainting.png');
ArtworkImages["Glowing Painting"] = require('./Artwork/RealGlowingPainting.png');
ArtworkImages["Flowery Painting"] = require('./Artwork/RealFloweryPainting.png');
ArtworkImages["Fake Graceful Painting"] = require('./Artwork/FakeGracefulPainting.png');
ArtworkImages["Graceful Painting"] = require('./Artwork/RealGracefulPainting.png');
ArtworkImages["Fake Jolly Painting"] = require('./Artwork/FakeJollyPainting.png');
ArtworkImages["Jolly Painting"] = require('./Artwork/RealJollyPainting.png');
ArtworkImages["Mysterious Painting"] = require('./Artwork/RealMysteriousPainting.png');
ArtworkImages["Moody Painting"] = require('./Artwork/RealMoodyPainting.png');
ArtworkImages["Fake Moving Painting"] = require('./Artwork/FakeMovingPainting.png');
ArtworkImages["Moving Painting"] = require('./Artwork/RealMovingPainting.png');
ArtworkImages["Nice Painting"] = require('./Artwork/RealNicePainting.png');
ArtworkImages["Perfect Painting"] = require('./Artwork/RealPerfectPainting.png');
ArtworkImages["Proper Painting"] = require('./Artwork/RealProperPainting.png');
ArtworkImages["Fake Quaint Painting"] = require('./Artwork/FakeQuaintPainting.png');
ArtworkImages["Quaint Painting"] = require('./Artwork/RealQuaintPainting.png');
ArtworkImages["Fake Scary Painting"] = require('./Artwork/FakeScaryPainting.png');
ArtworkImages["Scary Painting"] = require('./Artwork/RealScaryPainting.png');
ArtworkImages["Fake Scenic Painting"] = require('./Artwork/FakeScenicPainting.png');
ArtworkImages["Scenic Painting"] = require('./Artwork/RealScenicPainting.png');
ArtworkImages["Fake Serene Painting"] = require('./Artwork/FakeSerenePainting.png');
ArtworkImages["Serene Painting"] = require('./Artwork/RealSerenePainting.png');
ArtworkImages["Sinking Painting"] = require('./Artwork/RealSinkingPainting.png');
ArtworkImages["Fake Solemn Painting"] = require('./Artwork/FakeSolemnPainting.png');
ArtworkImages["Solemn Painting"] = require('./Artwork/RealSolemnPainting.png');
ArtworkImages["Twinkling Painting"] = require('./Artwork/RealTwinklingPainting.png');
ArtworkImages["Warm Painting"] = require('./Artwork/RealWarmPainting.png');
ArtworkImages["Fake Wild Painting"] = require('./Artwork/FakeWildPainting.png');
ArtworkImages["Wild Painting"] = require('./Artwork/RealWildPainting.png');
ArtworkImages["Fake Wild Painting"] = require('./Artwork/FakeWildPainting.png');
ArtworkImages["Wild Painting"] = require('./Artwork/RealWildPainting.png');
ArtworkImages["Fake Wistful Painting"] = require('./Artwork/FakeWistfulPainting.png');
ArtworkImages["Wistful Painting"] = require('./Artwork/RealWistfulPainting.png');
ArtworkImages["Worthy Painting"] = require('./Artwork/RealWorthyPainting.png');
ArtworkImages["Fake Ancient Statue"] = require('./Artwork/FakeAncientStatue.png');
ArtworkImages["Ancient Statue"] = require('./Artwork/RealAncientStatue.png');
ArtworkImages["Fake Beautiful Statue"] = require('./Artwork/FakeBeautifulStatue.png');
ArtworkImages["Beautiful Statue"] = require('./Artwork/RealBeautifulStatue.png');
ArtworkImages["Familiar Statue"] = require('./Artwork/RealFamiliarStatue.png');
ArtworkImages["Fake Gallant Statue"] = require('./Artwork/FakeGallantStatue.png');
ArtworkImages["Gallant Statue"] = require('./Artwork/RealGallantStatue.png');
ArtworkImages["Great Statue"] = require('./Artwork/RealGreatStatue.png');
ArtworkImages["Fake Informative Statue"] = require('./Artwork/FakeInformativeStatue.png');
ArtworkImages["Informative Statue"] = require('./Artwork/RealInformativeStatue.png');
ArtworkImages["Fake Motherly Statue"] = require('./Artwork/FakeMotherlyStatue.png');
ArtworkImages["Motherly Statue"] = require('./Artwork/RealMotherlyStatue.png');
ArtworkImages["Fake Mystic Statue"] = require('./Artwork/FakeMysticStatue.png');
ArtworkImages["Mystic Statue"] = require('./Artwork/RealMysticStatue.png');
ArtworkImages["Fake Robust Statue"] = require('./Artwork/FakeRobustStatue.png');
ArtworkImages["Robust Statue"] = require('./Artwork/RealRobustStatue.png');
ArtworkImages["Fake Rock-Head Statue"] = require('./Artwork/FakeRock-HeadStatue.png');
ArtworkImages["Rock-Head Statue"] = require('./Artwork/RealRock-HeadStatue.png');
ArtworkImages["Fake Tremendous Statue"] = require('./Artwork/FakeTremendousStatue.png');
ArtworkImages["Tremendous Statue"] = require('./Artwork/RealTremendousStatue.png');
ArtworkImages["Fake Valiant Statue"] = require('./Artwork/FakeValiantStatue.png');
ArtworkImages["Valiant Statue"] = require('./Artwork/RealValiantStatue.png');
ArtworkImages["Fake Warrior Statue"] = require('./Artwork/FakeWarriorStatue.png');
ArtworkImages["Warrior Statue"] = require('./Artwork/RealWarriorStatue.png');

export default ArtworkImages;