import { ImageSourcePropType } from "react-native";

export interface IDictionary {
    [name: string]: ImageSourcePropType;
}

const FossilImages: IDictionary = {};

FossilImages["Acanthostega"] = require('./Fossil/Acanthostega.png');
FossilImages["Amber"] = require('./Fossil/Amber.png');
FossilImages["Ammonite"] = require('./Fossil/Ammonite.png');
FossilImages["Anomalocaris"] = require('./Fossil/Anomalocaris.png');
FossilImages["Archaeopteryx"] = require('./Fossil/Archaeopteryx.png');
FossilImages["Australopith"] = require('./Fossil/Australopith.png');
FossilImages["Coprolite"] = require('./Fossil/Coprolite.png');
FossilImages["Dinosaur Track"] = require('./Fossil/DinosaurTrack.png');
FossilImages["Dunkleosteus"] = require('./Fossil/Dunkleosteus.png');
FossilImages["Eusthenopteron"] = require('./Fossil/Eusthenopteron.png');
FossilImages["Juramaia"] = require('./Fossil/Juramaia.png');
FossilImages["Myllokunmingia"] = require('./Fossil/Myllokunmingia.png');
FossilImages["Shark-Tooth Pattern"] = require('./Fossil/Shark-ToothPattern.png');
FossilImages["Trilobite"] = require('./Fossil/Trilobite.png');
FossilImages["Ankylo Skull"] = require('./Fossil/AnkyloSkull.png');
FossilImages["Ankylo Torso"] = require('./Fossil/AnkyloTorso.png');
FossilImages["Ankylo Tail"] = require('./Fossil/AnkyloTail.png');
FossilImages["Archelon Skull"] = require('./Fossil/ArchelonSkull.png');
FossilImages["Archelon Tail"] = require('./Fossil/ArchelonTail.png');
FossilImages["Brachio Skull"] = require('./Fossil/BrachioSkull.png');
FossilImages["Brachio Chest"] = require('./Fossil/BrachioChest.png');
FossilImages["Brachio Pelvis"] = require('./Fossil/BrachioPelvis.png');
FossilImages["Brachio Tail"] = require('./Fossil/BrachioTail.png');
FossilImages["Deinony Torso"] = require('./Fossil/DeinonyTorso.png');
FossilImages["Deinony Tail"] = require('./Fossil/DeinonyTail.png');
FossilImages["Dimetrodon Skull"] = require('./Fossil/DimetrodonSkull.png');
FossilImages["Dimetrodon Torso"] = require('./Fossil/DimetrodonTorso.png');
FossilImages["Diplo Skull"] = require('./Fossil/DiploSkull.png');
FossilImages["Diplo Neck"] = require('./Fossil/DiploNeck.png');
FossilImages["Diplo Chest"] = require('./Fossil/DiploChest.png');
FossilImages["Diplo Pelvis"] = require('./Fossil/DiploPelvis.png');
FossilImages["Diplo Tail"] = require('./Fossil/DiploTail.png');
FossilImages["Diplo Tail Tip"] = require('./Fossil/DiploTailTip.png');
FossilImages["Iguanodon Skull"] = require('./Fossil/IguanodonSkull.png');
FossilImages["Iguanodon Torso"] = require('./Fossil/IguanodonTorso.png');
FossilImages["Iguanodon Tail"] = require('./Fossil/IguanodonTail.png');
FossilImages["Mammoth Skull"] = require('./Fossil/MammothSkull.png');
FossilImages["Mammoth Torso"] = require('./Fossil/MammothTorso.png');
FossilImages["Megacero Skull"] = require('./Fossil/MegaceroSkull.png');
FossilImages["Megacero Torso"] = require('./Fossil/MegaceroTorso.png');
FossilImages["Megacero Tail"] = require('./Fossil/MegaceroTail.png');
FossilImages["Left Megalo Side"] = require('./Fossil/LeftMegaloSide.png');
FossilImages["Right Megalo Side"] = require('./Fossil/RightMegaloSide.png');
FossilImages["Ophthalmo Skull"] = require('./Fossil/OphthalmoSkull.png');
FossilImages["Ophthalmo Torso"] = require('./Fossil/OphthalmoTorso.png');
FossilImages["Pachysaurus Skull"] = require('./Fossil/PachysaurusSkull.png');
FossilImages["Pachysaurus Tail"] = require('./Fossil/PachysaurusTail.png');
FossilImages["Parasaur Skull"] = require('./Fossil/ParasaurSkull.png');
FossilImages["Parasaur Torso"] = require('./Fossil/ParasaurTorso.png');
FossilImages["Parasaur Tail"] = require('./Fossil/ParasaurTail.png');
FossilImages["Plesio Skull"] = require('./Fossil/PlesioSkull.png');
FossilImages["Plesio Tail"] = require('./Fossil/PlesioTail.png');
FossilImages["Plesio Body"] = require('./Fossil/PlesioBody.png');
FossilImages["Right Ptera Wing"] = require('./Fossil/RightPteraWing.png');
FossilImages["Ptera Body"] = require('./Fossil/PteraBody.png');
FossilImages["Left Ptera Wing"] = require('./Fossil/LeftPteraWing.png');
FossilImages["Right Quetzal Wing"] = require('./Fossil/RightQuetzalWing.png');
FossilImages["Quetzal Torso"] = require('./Fossil/QuetzalTorso.png');
FossilImages["Left Quetzal Wing"] = require('./Fossil/LeftQuetzalWing.png');
FossilImages["Sabertooth Skull"] = require('./Fossil/SabertoothSkull.png');
FossilImages["Sabertooth Tail"] = require('./Fossil/SabertoothTail.png');
FossilImages["Spino Skull"] = require('./Fossil/SpinoSkull.png');
FossilImages["Spino Torso"] = require('./Fossil/SpinoTorso.png');
FossilImages["Spino Tail"] = require('./Fossil/SpinoTail.png');
FossilImages["Stego Skull"] = require('./Fossil/StegoSkull.png');
FossilImages["Stego Torso"] = require('./Fossil/StegoTorso.png');
FossilImages["Stego Tail"] = require('./Fossil/StegoTail.png');
FossilImages["Tricera Skull"] = require('./Fossil/TriceraSkull.png');
FossilImages["Tricera Torso"] = require('./Fossil/TriceraTorso.png');
FossilImages["Tricera Tail"] = require('./Fossil/TriceraTail.png');
FossilImages["T. Rex Skull"] = require('./Fossil/T.RexSkull.png');
FossilImages["T. Rex Torso"] = require('./Fossil/T.RexTorso.png');
FossilImages["T. Rex Tail"] = require('./Fossil/T.RexTail.png');

export default FossilImages;