/**
 * Animal Crossing API
 * Swagger page for the Animal Crossing API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
export interface MonthsAvaliable {
    jan: boolean;
    feb: boolean;
    mar: boolean;
    apr: boolean;
    may: boolean;
    jun: boolean;
    jul: boolean;
    aug: boolean;
    sep: boolean;
    oct: boolean;
    nov: boolean;
    dec: boolean;
}

export interface CritterCollectionModel { 
    id: number;
    name: string;
    value: number;
    locationName: string;
    location: number;
    shadowSize: number;
    shadowSizeName: string;
    time: string;
    catchStartTime: Array<number>;
    catchEndTime: Array<number>;
    monthsAvailable: MonthsAvaliable;
    rarity: number;
    rarityName: string;
    weather: string;
}