/**
 * Animal Crossing API
 * Swagger page for the Animal Crossing API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface FishModel { 
    fishId: number;
    fishName: string;
    season?: number;
    seasonName?: string;
    location?: number;
    locationName?: string;
    value?: number;
    catchStartTime?: number;
    catchEndTime?: number;
    shadowSize?: number;
    shadowSizeName?: string;
    weather?: number;
    weatherName?: string;
    rarity?: number;
    rarityName?: string;
    image: string;
}